-- 医生评价表
CREATE TABLE IF NOT EXISTS `doctor_review` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `registration_id` bigint DEFAULT NULL COMMENT '挂号ID',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名',
  `doctor_id` bigint DEFAULT NULL COMMENT '医生ID',
  `doctor_name` varchar(64) DEFAULT NULL COMMENT '医生姓名',
  `department_id` bigint DEFAULT NULL COMMENT '科室ID',
  `department_name` varchar(64) DEFAULT NULL COMMENT '科室名称',
  `rating` int DEFAULT NULL COMMENT '评分 1-5星',
  `content` text COMMENT '评价内容',
  `images` varchar(1024) DEFAULT NULL COMMENT '图片URL，多个逗号分隔',
  `status` int DEFAULT '0' COMMENT '状态 0待审核 1已通过 2已驳回',
  `reply` varchar(1024) DEFAULT NULL COMMENT '管理员回复',
  `reply_time` datetime DEFAULT NULL COMMENT '回复时间',
  `his_sync_status` int DEFAULT '0' COMMENT 'HIS同步状态 0未同步 1已同步',
  `his_sync_time` datetime DEFAULT NULL COMMENT 'HIS同步时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int DEFAULT '0' COMMENT '逻辑删除 0未删除 1已删除',
  PRIMARY KEY (`id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_doctor_id` (`doctor_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生评价表';

-- 投诉建议表
CREATE TABLE IF NOT EXISTS `complaint` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `complaint_no` varchar(64) DEFAULT NULL COMMENT '投诉单号',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名',
  `patient_phone` varchar(32) DEFAULT NULL COMMENT '患者手机号',
  `type` int DEFAULT '1' COMMENT '类型 1投诉 2建议',
  `target_type` int DEFAULT '1' COMMENT '投诉对象类型 1科室 2医生',
  `department_id` bigint DEFAULT NULL COMMENT '科室ID',
  `department_name` varchar(64) DEFAULT NULL COMMENT '科室名称',
  `doctor_id` bigint DEFAULT NULL COMMENT '医生ID',
  `doctor_name` varchar(64) DEFAULT NULL COMMENT '医生姓名',
  `title` varchar(255) DEFAULT NULL COMMENT '标题',
  `content` text COMMENT '问题描述',
  `images` varchar(1024) DEFAULT NULL COMMENT '图片URL，多个逗号分隔',
  `status` int DEFAULT '0' COMMENT '状态 0待处理 1处理中 2已处理 3已关闭',
  `handle_user_id` bigint DEFAULT NULL COMMENT '处理人ID',
  `handle_user_name` varchar(64) DEFAULT NULL COMMENT '处理人姓名',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `reply` varchar(1024) DEFAULT NULL COMMENT '回复内容',
  `reply_time` datetime DEFAULT NULL COMMENT '回复时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `deleted` int DEFAULT '0' COMMENT '逻辑删除 0未删除 1已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_complaint_no` (`complaint_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投诉建议表';
